
#include "io430.h"

/*

unsigned const char graphics0[] = { 
                              254,
                              242,
                              18,
                              2,
                              2,
                              194,
                              34,
                              34,
                              66,
                              2,
                              130,
                              226,
                              130,
                              130,
                              2,
                              130,
                              130,
                              130,
                              130,
                              2,
                              2,
                              130,
                              226,
                              130,
                              130,
                              2,
                              130,
                              2,
                              2,
                              2,
                              130,
                              2,
                              2,
                              2,
                              130,
                              130,
                              130,
                              2,
                              2,
                              18,
                              242,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              254,
                              0,
                              254,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              242,
                              18,
                              2,
                              2,
                              194,
                              34,
                              34,
                              66,
                              2,
                              2,
                              2,
                              130,
                              130,
                              130,
                              2,
                              2,
                              2,
                              242,
                              2,
                              2,
                              2,
                              2,
                              130,
                              130,
                              2,
                              2,
                              2,
                              130,
                              2,
                              130,
                              130,
                              2,
                              2,
                              2,
                              2,
                              130,
                              130,
                              130,
                              2,
                              2,
                              2,
                              162,
                              2,
                              2,
                              2,
                              2,
                              130,
                              130,
                              130,
                              242,
                              2,
                              2,
                              18,
                              242,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                              2,
                            }; 
unsigned const char graphics1[] = { 
                              255,
                              127,
                              64,
                              0,
                              0,
                              8,
                              17,
                              18,
                              12,
                              0,
                              0,
                              15,
                              16,
                              16,
                              0,
                              12,
                              18,
                              18,
                              18,
                              31,
                              0,
                              0,
                              15,
                              16,
                              16,
                              0,
                              15,
                              16,
                              16,
                              8,
                              31,
                              0,
                              0,
                              19,
                              18,
                              20,
                              12,
                              0,
                              0,
                              64,
                              127,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              255,
                              0,
                              255,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              127,
                              64,
                              0,
                              0,
                              8,
                              17,
                              18,
                              12,
                              0,
                              0,
                              15,
                              16,
                              16,
                              16,
                              15,
                              0,
                              0,
                              31,
                              0,
                              0,
                              0,
                              15,
                              18,
                              18,
                              19,
                              0,
                              0,
                              31,
                              1,
                              0,
                              0,
                              31,
                              0,
                              0,
                              15,
                              16,
                              16,
                              16,
                              15,
                              0,
                              0,
                              31,
                              0,
                              0,
                              0,
                              15,
                              16,
                              16,
                              16,
                              31,
                              0,
                              0,
                              64,
                              127,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                            }; 
unsigned const char graphics2[] = { 
                              255,
                              240,
                              16,
                              16,
                              16,
                              32,
                              192,
                              0,
                              0,
                              240,
                              0,
                              0,
                              0,
                              96,
                              144,
                              16,
                              32,
                              0,
                              0,
                              0,
                              192,
                              48,
                              192,
                              0,
                              0,
                              0,
                              240,
                              16,
                              16,
                              16,
                              224,
                              0,
                              0,
                              240,
                              48,
                              192,
                              0,
                              0,
                              0,
                              192,
                              48,
                              240,
                              0,
                              0,
                              240,
                              144,
                              144,
                              144,
                              0,
                              0,
                              240,
                              16,
                              16,
                              16,
                              32,
                              192,
                              0,
                              0,
                              255,
                              0,
                              255,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              240,
                              144,
                              144,
                              144,
                              0,
                              0,
                              128,
                              64,
                              64,
                              128,
                              0,
                              0,
                              128,
                              64,
                              64,
                              128,
                              0,
                              0,
                              128,
                              64,
                              64,
                              64,
                              248,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              192,
                              32,
                              16,
                              16,
                              16,
                              32,
                              192,
                              0,
                              64,
                              240,
                              72,
                              72,
                              64,
                              240,
                              72,
                              72,
                              0,
                            }; 
unsigned const char graphics3[] = { 
                              255,
                              143,
                              136,
                              136,
                              136,
                              132,
                              131,
                              128,
                              128,
                              143,
                              128,
                              128,
                              128,
                              132,
                              136,
                              137,
                              134,
                              128,
                              140,
                              131,
                              130,
                              130,
                              130,
                              131,
                              140,
                              128,
                              143,
                              129,
                              129,
                              131,
                              140,
                              128,
                              128,
                              143,
                              128,
                              128,
                              131,
                              140,
                              131,
                              128,
                              128,
                              143,
                              128,
                              128,
                              143,
                              136,
                              136,
                              136,
                              128,
                              128,
                              143,
                              136,
                              136,
                              136,
                              132,
                              131,
                              128,
                              128,
                              255,
                              0,
                              255,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              15,
                              0,
                              0,
                              0,
                              0,
                              0,
                              7,
                              9,
                              9,
                              9,
                              0,
                              0,
                              7,
                              9,
                              9,
                              9,
                              0,
                              0,
                              7,
                              8,
                              8,
                              8,
                              15,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              3,
                              4,
                              8,
                              8,
                              8,
                              4,
                              3,
                              0,
                              0,
                              15,
                              0,
                              0,
                              0,
                              15,
                              0,
                              0,
                              0,
                            }; 
unsigned const char graphics4[] = { 
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              255,
                              0,
                              0,
                              0,
                              0,
                              0,
                              248,
                              136,
                              136,
                              136,
                              112,
                              0,
                              0,
                              192,
                              160,
                              160,
                              192,
                              0,
                              0,
                              252,
                              0,
                              0,
                              0,
                              192,
                              160,
                              160,
                              192,
                              0,
                              0,
                              32,
                              160,
                              160,
                              160,
                              192,
                              0,
                              0,
                              192,
                              160,
                              32,
                              32,
                              0,
                              0,
                              192,
                              160,
                              160,
                              192,
                              0,
                              0,
                              0,
                              0,
                              0,
                              0,
                              224,
                              16,
                              8,
                              8,
                              8,
                              16,
                              224,
                              0,
                              0,
                              224,
                              64,
                              32,
                              32,
                              192,
                              0,
                              0,
                            }; 
unsigned const char graphics5[] = { 
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              128,
                              191,
                              160,
                              160,
                              160,
                              160,
                              160,
                              167,
                              160,
                              160,
                              161,
                              166,
                              160,
                              160,
                              163,
                              164,
                              164,
                              164,
                              160,
                              160,
                              167,
                              160,
                              160,
                              160,
                              163,
                              164,
                              164,
                              164,
                              160,
                              160,
                              163,
                              164,
                              164,
                              164,
                              167,
                              160,
                              160,
                              164,
                              164,
                              165,
                              163,
                              160,
                              160,
                              163,
                              164,
                              164,
                              164,
                              160,
                              160,
                              160,
                              160,
                              160,
                              160,
                              161,
                              162,
                              164,
                              164,
                              164,
                              162,
                              161,
                              160,
                              160,
                              167,
                              160,
                              160,
                              160,
                              167,
                              160,
                              160,
                            }; 
unsigned const char graphics6[] = { 
                              255,
                              252,
                              32,
                              80,
                              136,
                              4,
                              0,
                              0,
                              224,
                              80,
                              80,
                              96,
                              0,
                              48,
                              192,
                              0,
                              192,
                              48,
                              0,
                              0,
                              0,
                              0,
                              0,
                              248,
                              4,
                              4,
                              4,
                              248,
                              0,
                              16,
                              32,
                              192,
                              32,
                              16,
                              0,
                              0,
                              144,
                              80,
                              80,
                              80,
                              224,
                              0,
                              16,
                              252,
                              18,
                              18,
                              0,
                              216,
                              36,
                              36,
                              36,
                              216,
                              0,
                              0,
                              240,
                              40,
                              36,
                              36,
                              196,
                              0,
                              0,
                              224,
                              80,
                              80,
                              96,
                              0,
                              0,
                              4,
                              4,
                              196,
                              52,
                              12,
                              0,
                              0,
                              60,
                              36,
                              36,
                              36,
                              196,
                              0,
                              0,
                              8,
                              36,
                              36,
                              36,
                              216,
                              0,
                              0,
                              8,
                              4,
                              132,
                              68,
                              56,
                              0,
                              0,
                              192,
                              176,
                              140,
                              252,
                              128,
                              0,
                              0,
                              224,
                              16,
                              16,
                              16,
                              0,
                              0,
                              60,
                              36,
                              36,
                              36,
                              196,
                              0,
                              0,
                              144,
                              80,
                              80,
                              80,
                              224,
                              0,
                              0,
                              240,
                              40,
                              36,
                              36,
                              196,
                              0,
                            }; 
unsigned const char graphics7[] = { 
                              31,
                              19,
                              16,
                              16,
                              17,
                              18,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              16,
                              16,
                              28,
                              19,
                              16,
                              16,
                              16,
                              16,
                              16,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              17,
                              16,
                              18,
                              17,
                              16,
                              17,
                              18,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              19,
                              16,
                              16,
                              19,
                              16,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              17,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              17,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              16,
                              16,
                              16,
                              19,
                              16,
                              16,
                              16,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              17,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              17,
                              16,
                              16,
                              18,
                              19,
                              18,
                              18,
                              18,
                              16,
                              16,
                              16,
                              16,
                              16,
                              19,
                              16,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              17,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              19,
                              16,
                              16,
                              17,
                              18,
                              18,
                              18,
                              17,
                              16,
                            }; 

unsigned const char * graphics_ptr[] = {graphics0, graphics1, graphics2, 
                                        graphics3, graphics4, graphics5,
                                        graphics6, graphics7};

*/

typedef struct
{
   unsigned char x;
   unsigned char y;
} xy_pair_t;

typedef struct
{
   xy_pair_t top_left;
   xy_pair_t bottom_right;
} box_t;

typedef struct
{
   unsigned char feed_enabled;
   unsigned char release_enabled;
   unsigned char armed_enabled;
} lcd_state_t;

lcd_state_t lcd_state = { 0, 1, 1 };

const  box_t feed_off_box    = { { 108, 17 } , { 127, 28 } } ;
const box_t release_on_box = { { 108, 33 } , { 127, 44 } } ;
const box_t dis_box     = { {   1, 20 } , {  17, 28 } } ;
const box_t full_box = { { 0, 0, } , {127, 63} };

void setupSpi()
{
   // setup SPI
   USICKCTL = 0x48; // main clock, divide by 128
   USICTL0  = 0xEA; //11101010 spi outputs enabled; not held in reset state
   USICTL1 |= 0x80; // data captured on leading clock edge
   //USICTL0 &= ~0x01; // enable spi
   P1OUT &= ~0x10;
}

void sendSpiChar(unsigned char c)
{
   USISRL = c;     // set the output shift register with our 8 bits
   P1OUT |= 0x10; // Slave_Select_BAR
   USICTL0 &= ~0x01; // break out of reset / disabled state
   int j = 1; // need this or spi will break
   USICNT = 0x08;  // we have 8 bits to send
   while ((USICNT & 0x1f) > 0); // make sure we sent all 8 bits
   //for (int i = 4; i > 0; i--);
   int i = 1; // need this or spi will break
   // disable spi
   USICTL0 |= 0x01;
   //P1OUT &= ~0x10;  // Slave_Select_BAR
   return;
}

/*
void sendSpiString(char * sz)
{
   int i = 0;
   while (*(sz + i)) sendSpiChar(*(sz + i++));
}
*/

void sendSpiStringLen(unsigned char * sz, int len)
{
  int i = 0;
  for (; len--; len > 0) 
  {
    sendSpiChar(*(sz + i++));
    for (int i = 0; i < 32000; i++); 
  }
}

unsigned char LCD_COLUMNS  = 128;
unsigned char LCD_SEGMENTS =   8;


// boxes must be same size, but we don't check due to code size limitations
void writeBoxFromGraphics(const box_t * source, const box_t * dest)
{
  /*
  for (unsigned char i = dest->top_left.x; i <= dest->bottom_right.x; i++)
  {
     unsigned char page_start = dest->top_left.y / 8;
     unsigned char page_end   = dest->bottom_right.y / 8;
     unsigned char row_number_start_page;
     unsigned char row_number_stop_page;
     
     unsigned char dest_top_left_y_mod = dest->top_left.y % 8;
     
     for (int x = page_start ;  x <= page_end; x++)
     {
        row_number_start_page = 0;
        row_number_stop_page  = LCD_SEGMENTS - 1;
       
        sendSpiChar(0xb0 | x); // set page no
        sendSpiChar(0x10 | (i >> 4));  // set column no.
        sendSpiChar(0x00 | (i & 0x0f));// set column no.
        P1OUT |= 0x08; // lcd a0 pin = 1
        unsigned char graph_orig     = graphics_ptr[x][i];
        unsigned char graph_new_full = graph_orig;
        
        if ( x == page_start) // check to see if we need to move the row_number_start_page to clip copying
        {
           row_number_start_page = dest_top_left_y_mod % 8;
        }
        
        if (x == page_end) // check to see if we need to move the row_number_stop_page to clip copying
        {
           row_number_stop_page  = dest->bottom_right.y % 8;
        }
        
        // form copy mask
        unsigned char copy_mask = 0;
        for (int j = row_number_start_page; j <= row_number_stop_page; j++)
        {
           copy_mask |= 1 << j;
        }

        graph_new_full &= ~copy_mask; // mark zeros where we will place the new box
         
        // find differential within page from source to destination
        int differential = dest_top_left_y_mod - source->top_left.y % 8;
      
        // page from which we source the 0th vertical pixel in the dest page
        unsigned char from_page = (source->top_left.y + 8 * (x - page_start) - ( dest_top_left_y_mod - row_number_start_page) ) / 8;
        
        // form the page we get the new graphics from
        unsigned char box_graphics = graphics_ptr[from_page][i];
        
        // might need to flip what is in the if statement with whats in the else if
        // shift to take into account the differential
        if (differential > 0)
        {
           box_graphics  = box_graphics << differential;
           box_graphics |= graphics_ptr[from_page - 1][i] >> (8 - differential);
        }
        else
        {
           box_graphics  = box_graphics >> (-1 * differential ) ;
           box_graphics |= graphics_ptr[from_page + 1][i] << (8 + differential);
        }
        
        box_graphics &= copy_mask;
        graph_new_full |= box_graphics;
        
        // combine box graphics with new graphics
        
        sendSpiChar(graph_new_full);
        P1OUT &= ~0x08; // lcd a0 pin = 0
     }
  }
  
  */
}

 unsigned char lcdInit[] = {
                             0x40,
                             0xa1,
                             0xc0,
                             0xa6,
                             0xa2,
                             0x2f,
                             0xf8,
                             0x00,
                             0x27,
                             0x81,
                             0x16,
                             0xac,
                             0x00,
                             0xaf,
                         };

int main( void )
{
  // Stop watchdog timer to prevent time out reset
  WDTCTL = WDTPW + WDTHOLD;
  P1DIR  = 0x1f;
  P1OUT  = 0x01; // enable flag for SPI & reset inactive
  for (int i = 0; i < 100; i++);
  
  
  setupSpi();
  
  sendSpiStringLen(lcdInit, 14);
  sendSpiChar(0xb0); // page 0
  // write a block to ram
  
 
  
  
  while (1)
  {
      // if (lcd_state.armed_enabled)
      //{
         //writeBoxFromGraphics(feed_box);
      //}
      
     writeBoxFromGraphics(&full_box, &full_box);
    
      if (lcd_state.feed_enabled)
         writeBoxFromGraphics( &release_on_box, &feed_off_box );
      else
         writeBoxFromGraphics( &feed_off_box, &feed_off_box);
      
      /*
      if (!lcd_state.release_enabled)
         writeBoxFromGraphics( &feed_off_box, &release_on_box );
      else
         writeBoxFromGraphics( &release_on_box, &release_on_box);
      */
      
      lcd_state.feed_enabled = !lcd_state.feed_enabled;
      
      P1OUT = P1OUT ^ 0x06;
  }
   
  return 0;
}

